#!/bin/bash
# 关于 texlive/xelatex 的中文输入
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#%只要有相应的字体文档，不需要使用CJKutf8，直接由 xelatex 产生pdf文档	%
#%检索安装字体用命令 fc-list | grep'字体名' 即可知道可用字体		%
#%									%
#\usepackage{fontspec}							%
#\setmainfont[Mapping=tex-text]{LiSu}					%
#%\setmainfont[Mapping=tex-text]{Adobe 宋体 Std}	%article用字体	%
#%\setsansfont[Mapping=tex-text]{Adobe 黑体 Std}	 %Beamer用字体	%
#%									%
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# echo $1
Figures=Figures/
#if [[ "$2" ]]; then
#	Figures=`echo $2 | awk -F "=" '{print $2}'`
	if [ -d $Figures ]; then
		cd $Figures && Figures=`pwd`&& cd ..
#	else
#		echo "There is NO Figures_Dir"
#		exit
	fi
#fi
while [[ ! -d $Figures ]];
do
	# echo "The Directory of Figures"
	read -p "The Directory of Graphics: " var_Fig_Dir
	Figures=$var_Fig_Dir #| awk -F "=" '{print $2}'`
done
# echo $Figures
# exit

References=/home/jun-jiang/Documents/Reference
#if [[ "$3" ]]; then
#	References=`echo $3 | awk -F "=" '{print $2}'`
#	if [ -d $References ]; then
##		cd $Figures && pwd
#		References=$References
##		echo $References
#	else
#		echo "There is NO References_Dir"
#		exit
#	fi
#fi
while [[ ! -d $References ]];
do
	# echo "The Directory of Figures"
	read -p "The Directory of Bibliography: " var_Ref_Dir
	References=$var_Ref_Dir #| awk -F "=" '{print $2}'`
done
# echo $References
# exit

PATH_Local=`pwd`
test -s Beamer_Template/Beamer_Template-Preamble_tmp && mv Beamer_Template/Beamer_Template-Preamble_tmp  Beamer_Template/Beamer_Template-Preamble.tex
	cp Beamer_Template/Beamer_Template-Preamble.tex  Beamer_Template/Beamer_Template-Preamble_tmp
sed -e "s#\$PATHPWD#`echo $Figures `#" Beamer_Template/Beamer_Template-Preamble_tmp > Beamer_Template/Beamer_Template-Preamble.tex
# PATHFIG=`pwd`
# test -e Beamer_Template/Beamer_Template-Preamble.tex &&  awk '{if(NR>=117 && NR<=117) print "\graphicspath{{" "$PATHFIG" "/}}"}' Beamer_Template/Beamer_Template-Preamble.tex

test -s Beamer_Template/Beamer_3-Bibliography_tmp && mv Beamer_Template/Beamer_3-Bibliography_tmp  Beamer_Template/Beamer_3-Bibliography.tex
       	cp Beamer_Template/Beamer_3-Bibliography.tex  Beamer_Template/Beamer_3-Bibliography_tmp
cd $References && PATH_Reference=`pwd`
cd $PATH_Local && sed -e "s#\$PATHPWD#`echo $PATH_Reference`#g"  Beamer_Template/Beamer_3-Bibliography_tmp > Beamer_Template/Beamer_3-Bibliography.tex 

#exit
touch Beamer_Template/.tmp 
# test -s Beamer_Template/Beamer_2-Main.tex && sed 's/^\\input/%\\input/g' Beamer_Template/Beamer_2-Main.tex  > Beamer_Template/.tmp || echo "%Main_File"  > Beamer_Template/.tmp
test -e Beamer_Template/Beamer_2-Main.tex && echo "%Main_File"  > Beamer_Template/.tmp
sed '$a%%%%%%%%%%  '"$1"'   %%%%%%%%%%  \n\\\input{'"$1"'}' Beamer_Template/.tmp  > Beamer_Template/Beamer_2-Main.tex 
rm Beamer_Template/.tmp 

xelatex Beamer-Template_Main
bibtex  Beamer-Template_Main
xelatex Beamer-Template_Main
xelatex Beamer-Template_Main

rm -rf *.aux  *.bbl  *.dvi *.blg *.bcf *.out *.log *.nav *.thm *.snm *.toc *.*.xml *.*~ *~ .*.*.swp
cd Beamer_Template/
rm -rf *.aux  *.bbl  *.dvi *.blg *.bcf *.out *.log *.nav *.thm *.snm *.toc *.*.xml *.*~ *~ .*.*.swp
# cat Beamer_Template-Preamble_tmp
cp Beamer_Template-Preamble_tmp Beamer_Template-Preamble.tex && rm Beamer_Template-Preamble_tmp
cp Beamer_3-Bibliography_tmp Beamer_3-Bibliography.tex && rm Beamer_3-Bibliography_tmp 

cd ..
mv Beamer-Template_Main.pdf $1.pdf
evince $1.pdf &
